### ISSUE TITLE
Miscomputation on the probabilities

### ISSUE THREAD

**Issue by iNko97** [DeeKahy/poeGem#4]
Hi, just a quick input since I stumbled over your program.
Pretty cool project!

I saw that you compute the probabilities by averaging the chaos values over a certain threshold. Although this is very valid to get a "quick-glance" most valuable colour to transform, it is not mathematically correct and significantly impacts the odds for some colours.

To formalise this problem we draw 3 gems from a pool size depending on colour without repetition, and afterwards we pick the one with the highest chaos value. For example, if I were to draw both the highest-valued gem and the second highest-valued, I would not get any additional value compared to just having drawn the highest-valued.

The probability that $k$ is the highest-ranked gem, among $n$ total possible gems, in three draws without repetition is the following.
$P(X_{(3)} = k) = \frac{\binom{k-1}{2}}{\binom{n}{3}}$ if $k >= 3$
$P(X_{(3)} = k) = 0$ if $k < 3$

Let us take as an example the 32 red gems. We assign to each gem a value $k_{value}$ and rank them from 32 (best) to 0 (worst) value.

We compute the table for all 32 possible gems, and verify the sum is 1.

`([(3, 0.00020161290322580645),
  (4, 0.0006048387096774194),
  (5, 0.0012096774193548388),
  (6, 0.0020161290322580645),
  (7, 0.0030241935483870967),
  (8, 0.004233870967741936),
  (9, 0.00564516129032258),
  (10, 0.007258064516129033),
  (11, 0.009072580645161291),
  (12, 0.011088709677419355),
  (13, 0.013306451612903225),
  (14, 0.015725806451612902),
  (15, 0.018346774193548385),
  (16, 0.021169354838709676),
  (17, 0.024193548387096774),
  (18, 0.027419354838709678),
  (19, 0.030846774193548386),
  (20, 0.034475806451612905),
  (21, 0.038306451612903226),
  (22, 0.04233870967741935),
  (23, 0.04657258064516129),
  (24, 0.051008064516129034),
  (25, 0.055645161290322584),
  (26, 0.06048387096774194),
  (27, 0.0655241935483871),
  (28, 0.07076612903225807),
  (29, 0.07620967741935483),
  (30, 0.08185483870967741),
  (31, 0.08770161290322581),
  (32, 0.09375)],
 1.0)`

Now all that's left to do is multiply the probability by the value of the gem in descending order, until the breakpoint set by the user. For example, assuming a cutoff at 10 chaos and only 4 gems valued at [35, 20, 10, 10]:
$0.0938 * 35 + 0.0877 * 20 + 0.0819 * 10 + 0.0762 * 10 = 6.618$ chaos expected value.

**Comment by DeeKahy** [comment]
You are completely right, this is an oversight on my part.

Ive run a simulation of picking the most valuable gem out of 3 random results (for each colour) and it does seem to influence the results enough to be worth implementing.

**Comment by DeeKahy** [comment]
Okay a proper implementation is now in main and it matches up with the simulation i made. thank you again for pointing it out <3
